---
title: "Hierarchical clustering -- Which states in Nigeria have similar expenditure
  profile?"
description: |
  A short description of the post.
author:
  - name: Linus Agbleze
    url: https://agbleze.github.io/Portfolio/#work
date: 2022-07-18
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction to clustering analysis

Clustering analysis is one of the important exploratory data analysis you will consider undertaking in order to identify groupings in your dataset. It belongs to the segment of unsupervised classification which draws the data into clusters of similarity. Infact, many classification schemes have this underpinning of classifying a large set of individual elements or observations into a small number of classes. Talk of species classification, the periodic table, development index among others. Remember, it is groups of similarity. This notion also runs in business or rather dominates business decisions. Differential pricing, product and market segmentation among others require identifying the different groups present and tailoring policies that best serve each of them. So clustering analysis is important there!

That being said, there are typically two set of clustering techniques that are use to identify groups of similarity. Namely;

-   Hierarchical clustering
-   K-means clustering

In order to do a little deep dive, we will take them in turns. This tutorial will focus on hierarchical clustering where a tree structure is produce for the clusters -- dendrograms.


## Hierarchical clustering analysis

Hierarchical clustering is of two types; agglomerative nesting and divisive analysis. The two are oppose in terms of where formation of clusters begin from. 

* Agglomerative Nesting (AGNES) merges similar clusters beginning from the bottom-most, into nodes and in a sequential manner continue merging them until all clusters form a single root at the top of the tree.

* Divisive clustering also known as DIANA (Divise Analysis) runs in opposite direction to AGNES. The algorithm starts by disaggregating the root cluster, which is the single cluster containing all other clusters, into dissimilar clusters at each step (with each cluster being internally similar) until all the dissimilarity between clusters are completely exhausted. Thus, it ends with the leafs, which are  clusters at the bottom, entirely dissimilar to each other.

**So AGNES adds up similar cluster leafs to form a cluster node and then a root while DIANA divides a single cluster root into dissimilar cluster nodes and then finally cluster leafs. Thus, AGNES is favoured for finding small clusters while DIANA works well for large clusters.**

#### Workflow for hierarchical clustering analysis

In order to undertake hierarchical clustering, the data has to be cleaned and prepared for that purpose such that variables are comparable. This involve the following;

-   Data wraggling and transformation that results in a tidy data such that;
      * Each column is a variable
      * Each row is a recording or observation
      * Each cell is a data

- Standardizing / scaling the data
- Calculating dissimilarity measure between clusters

In measuring dissimilarity between clusters, different methods can be use and are required to be specified when using AGNES. The methods are identified as follows; 

* Maximum / complete linkage: uses the highest dissimilarity found between clusters after pairwise calculation of dissimilarities of elements in different clusters.

-   Minimum / single linkage: uses the least dissimilarity between clusters following similar method as complete linkage in calculating dissimilarity

-   Mean / average linkage: as the name suggests, uses average dissimilarity as distance between clusters after computing pairwise dissimilarity between observations in different clusters.

-   Centroid linkage: based on the dissimilarity between the centroid of clusters.

-   Ward's minimum variance: focuses on minimizing inward cluster difference by merging groups with least between-cluster distance.

The best way to understand the workflow and methods identified for computing hierarchical clustering is by practicing with a project. We are going to define a simple research that clustering analysis can be used for and go through the complete pipeline required to execute it. 

So let's take a break from the long discussion and start with  practicals.


## Research objective

-   To identify states in Nigeria with similar expenditure profile on petrol, kerosene and health (excluding insurance)

## Dataset

The dataset to be used for this tutorial is Living Standard Measurement Study (LSMS) for Nigeria. Specifically, we will use the General Household Survey, 2015-2016 Panel data which is the Wave 3. The dataset can be accessed from (<https://microdata.worldbank.org/index.php/catalog/2734/related-materials>).

#### Know the Metadata of your data

As part of most data science projects in the real world, background checks has to be done even before data exploration and analysis. We have covered our first step which is accessing the data. The data can even be provided to us by our client or project partner or whoever we are working for. But one thing that we will have to do ourselves is to familiarize ourselves with variable names used, questionnaire administered and its design, how data was collected, units of measurement for the various variables among several others. Understanding these elements will influence how we explore the data, organize it in terms of merging datasets and variables, and analyze it.

To do this for our dataset, we need to look at the documentation of the dataset which is also available on the site (<https://microdata.worldbank.org/index.php/catalog/2734/data-dictionary>).

After familiarizing ourselves with the metadata files, it is clear that the variables we want to analyze are in two different files namely sect8b_plantingw3.csv (contains expenditure on various fuels including kerosene and petrol among others) and sect8c_plantingw3.csv (contains expenditure on health). The dataset create opportunity for us to learn key skills of data wrangling and transformation before the actual clustering analysis. This is typical of many projects.

#### Project Tasks

-   Data wrangling and transformation
    -   Subseting dataset
    -   filtering dataset
    -   grouping dataset
    -   summarizing
-   Scaling dataset
-  Hierarchical clustering
    -   AGNES clustering
    -   DIANA clustering
-   Determining optimal clusters
-   Customizing visualization of clusters

#### Packages and libraries

Now that we know the tasks we will be undertaking, we have to install (if not already installed) and load the  libraries needed
